// Code generated by goctl. DO NOT EDIT.
// Source: usercenter.proto

package server

import (
	"context"

	"github.com/go-bineanshi/usercenter-rpc/internal/logic/registerloginrpc"
	"github.com/go-bineanshi/usercenter-rpc/internal/svc"
	"github.com/go-bineanshi/usercenter-rpc/types/usercenter"
)

type RegisterLoginRpcServer struct {
	svcCtx *svc.ServiceContext
	usercenter.UnimplementedRegisterLoginRpcServer
}

func NewRegisterLoginRpcServer(svcCtx *svc.ServiceContext) *RegisterLoginRpcServer {
	return &RegisterLoginRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RegisterLoginRpcServer) RegisterUser(ctx context.Context, in *usercenter.RegisterUserReq) (*usercenter.UserInfo, error) {
	l := registerloginrpclogic.NewRegisterUserLogic(ctx, s.svcCtx)
	return l.RegisterUser(in)
}

func (s *RegisterLoginRpcServer) LoginUser(ctx context.Context, in *usercenter.LoginUserReq) (*usercenter.UserInfo, error) {
	l := registerloginrpclogic.NewLoginUserLogic(ctx, s.svcCtx)
	return l.LoginUser(in)
}

func (s *RegisterLoginRpcServer) ChangeUserPassword(ctx context.Context, in *usercenter.ChangePasswordReq) (*usercenter.BaseMessage, error) {
	l := registerloginrpclogic.NewChangeUserPasswordLogic(ctx, s.svcCtx)
	return l.ChangeUserPassword(in)
}
