// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SysUsersColumns holds the columns for the "sys_users" table.
	SysUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Comment: "Status 1: normal 2: ban | 状态 1 正常 2 禁用", Default: 1},
		{Name: "nickname", Type: field.TypeString, Unique: true, Comment: "用户名称"},
		{Name: "password", Type: field.TypeString, Comment: "密码"},
		{Name: "avater", Type: field.TypeString, Nullable: true, Comment: "用户头像"},
	}
	// SysUsersTable holds the schema information for the "sys_users" table.
	SysUsersTable = &schema.Table{
		Name:       "sys_users",
		Columns:    SysUsersColumns,
		PrimaryKey: []*schema.Column{SysUsersColumns[0]},
	}
	// SysUserAuthsColumns holds the columns for the "sys_user_auths" table.
	SysUserAuthsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Comment: "Status 1: normal 2: ban | 状态 1 正常 2 禁用", Default: 1},
		{Name: "provider", Type: field.TypeEnum, Comment: "登录提供商", Enums: []string{"username", "phone", "email", "weixin"}},
		{Name: "account", Type: field.TypeString, Comment: "账号"},
		{Name: "user_id", Type: field.TypeUint64, Nullable: true},
	}
	// SysUserAuthsTable holds the schema information for the "sys_user_auths" table.
	SysUserAuthsTable = &schema.Table{
		Name:       "sys_user_auths",
		Columns:    SysUserAuthsColumns,
		PrimaryKey: []*schema.Column{SysUserAuthsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_user_auths_sys_users_auths",
				Columns:    []*schema.Column{SysUserAuthsColumns[6]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userauth_provider_account",
				Unique:  true,
				Columns: []*schema.Column{SysUserAuthsColumns[4], SysUserAuthsColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SysUsersTable,
		SysUserAuthsTable,
	}
)

func init() {
	SysUsersTable.Annotation = &entsql.Annotation{
		Table: "sys_users",
	}
	SysUserAuthsTable.ForeignKeys[0].RefTable = SysUsersTable
	SysUserAuthsTable.Annotation = &entsql.Annotation{
		Table: "sys_user_auths",
	}
}
